// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bjrpwswlcafpfdwhyraw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqcnB3c3dsY2FmcGZkd2h5cmF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTc0ODAsImV4cCI6MjA2OTQ3MzQ4MH0.hDaH7AUNAo8qbtTKt1s6UUhbrfUGVxuuNvEqucGcxvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);